# fabric-carpet but made as paper plugin
tweaks:
  # explosions will be cancelled at last tick
  # so it won't actually explode anything
  explosionNoBlockDamage: false
  # water can be placed if player is in creative
  # (in nether)
  creativeNetherWaterPlacement: false
  # removes any cooldown from items for players
  # that are in creative
  creativeNoItemCooldown: false
  # players in creative will open containers
  # regardless of it's block/lock state
  creativeOpenContainerForcibly: false
  # disables absolutely any changes in weather
  disableWeatherChange: false
  # snow, ice, fire, coral and turtle eggs
  # can't disappear, melt or fade away now
  # https://jd.papermc.io/paper/1.21/org/bukkit/event/block/BlockFadeEvent.html
  disableBlockFading: false

# customization for some commands
commands:
  item:
    # defaults to 1, takes {n} amount of levels
    # upon rename, set to -1 to don't take it all
    renameCost: 1

chat:
  public:
    # how message will be displayed for players in chat
    format: "<#554d96><name><reset> <dark_gray>»<reset> <gray><message></reset>"
  # /pm /msg /tell
  # TODO: implement actual functionality of private messaging
  private:
    # simply format in which it will be displayed for sender and receiver of message
    senderFormat: "<#eff542>[PM]<reset> <#554d96><sender><reset> <dark_gray>»<reset> <#554d96><receiver><reset>: <gray><message></reset>"
    receiverFormat: "<#eff542>[PM]<reset> <#554d96><receiver><reset> <dark_gray>«<reset> <#554d96><sender><reset>: <gray><message></reset>"
    # cooldown in seconds when people will forget about last message sender
    # used for /r /reply
    cooldown: 30

  modules:
    # :loc: -> [-103, 62, 1042]
    location: true
    # @shockpast -> yellow with sound, like discord mentions!
    mention:
      # key names from /playsound
      sound: "minecraft:block.amethyst_block.hit"
      # will search for: "@shockpast" "@Tony" "@Notch"
      prefix: "@"
      # on/off switch
      enabled: true

# things are not done, or shouldn't be used
features:
  custom_brand:
    enabled: false
    delay: 0 # long (in seconds, internally <delay * 20L>)
    period: 3 # long (in seconds, internally <delay * 20L>)
    names: # list of strings that will appear in brand
      - line 1
      - line 2
      - line 3
