name: RoflanUtils
version: '1.0-SNAPSHOT'
main: me.shockpast.roflan.Roflan
api-version: '1.21'
depend: [ ProtocolLib ] # required only for BrandRunnable
load: STARTUP
commands:
  vanish:
    description: ":)"
    usage: "/vanish [player]"
    aliases: [ cloak, v ]
    permission: roflan.command.vanish
    permission-message: "You do not have permission to vanish yourself or others."
  invsee:
    description: ":)"
    usage: "/invsee <player>"
    aliases: []
    permission: roflan.command.invsee
    permission-message: "You do not have permission to view other's player inventory."
  mute:
    description: ":)"
    usage: "/mute <player> [duration] [reason]"
    aliases: []
    permission: roflan.command.mute
    permission-message: "You do not have permission to mute other players."
  report:
    description: ":)"
    usage: "/report <send/close> <player/id> [reason]"
    aliases: []
    permission: roflan.command.report
    permission-message: "You do not have permission to report other players."
  item:
    description: ":)"
    usage: "/item <rename> <name>"
    aliases: []
    permission: roflan.command.item
    permission-message: "You do not have permission to use this command."
  tweak:
    description: ":)"
    usage: "/tweak [tweakName] <input>"
    aliases: []
    permission: roflan.command.tweak
    permission-message: "You do not have permission to use this command."
  fly:
    description: ":)"
    usage: "/fly"
    aliases: []
    permission: roflan.command.fly
    permission-message: "You do not have permission to fly around."