name: RoflanUtils
description: "I had to put there something :)"
version: "1.0.0"
main: me.shockpast.roflan.Roflan
api-version: '1.21'
author: "shockpast"
depend: [ ProtocolLib, PlaceholderAPI ]

commands:
  vanish:
    description: ":)"
    usage: "/vanish [player]"
    aliases: [ cloak, v ]
    permission: roflan.admin
    permission-message: "You do not have permission to vanish yourself or others."
  invsee:
    description: ":)"
    usage: "/invsee <player>"
    aliases: []
    permission: roflan.admin
    permission-message: "You do not have permission to view other's player inventory."
  item:
    description: ":)"
    usage: "/item <rename> <name>"
    aliases: []
    permission-message: "You do not have permission to use this command."
  tweak:
    description: ":)"
    usage: "/tweak [tweakName] <input>"
    aliases: []
    permission: roflan.admin
    permission-message: "You do not have permission to use this command."
  fly:
    description: ":)"
    usage: "/fly"
    aliases: []
    permission: roflan.admin
    permission-message: "You do not have permission to fly around."
  pm:
    description: ":)"
    usage: "/pm <player> <message>"
    aliases: [ msg, tell, whisper ]
    permission-message: "You do not have permission to send private messages."
  reply:
    description: ":)"
    usage: "/reply <message>"
    aliases: [ r ]
    permission-message: "You do not have permission to reply to private messages."

permissions:
  roflan.admin:
    default: op
    children:
      - roflan.command.fly
      - roflan.command.vanish
      - roflan.command.tweak
      - roflan.command.invsee