name: rofl
version: '1.0-SNAPSHOT'
main: me.shockpast.rofl.Rofl
api-version: '1.21'
commands:
  vanish:
    description: ":)"
    usage: "/vanish [player]"
    aliases: [ cloak, v ]
    permission: rofl.command.vanish
    permission-message: "You do not have permission to vanish yourself or others."
  invsee:
    description: ":)"
    usage: "/invsee <player>"
    aliases: []
    permission: rofl.command.invsee
    permission-message: "You do not have permission to view other's player inventory."
  mute:
    description: ":)"
    usage: "/mute <player> [duration] [reason]"
    aliases: []
    permission: rofl.command.mute
    permission-message: "You do not have permission to mute other players."
  report:
    description: ":)"
    usage: "/report <send/close> <player/id> [reason]"
    aliases: []
    permission: rofl.command.report
    permission-message: "You do not have permission to report other players."